// Unity build for CRuby extension
#include "../../src/glad.c"
#include "../../src/zenoo_window.c"
#include "../../src/zenoo_input.c"
#include "../../src/zenoo_vibration.c"
#include "../../src/zenoo_image.c"
#include "../../src/zenoo_gfx.c"
#include "../../src/zenoo_font.c"
#include "../../src/zenoo_audio.c"
#include "zenoo_ext.c"
