#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "glad/glad.h"

PFNGLGETSTRINGPROC glGetString = NULL;
PFNGLVIEWPORTPROC glViewport = NULL;
PFNGLCLEARCOLORPROC glClearColor = NULL;
PFNGLCLEARPROC glClear = NULL;
PFNGLFLUSHPROC glFlush = NULL;
PFNGLENABLEPROC glEnable = NULL;
PFNGLDISABLEPROC glDisable = NULL;
PFNGLBLENDFUNCPROC glBlendFunc = NULL;
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = NULL;
PFNGLSCISSORPROC glScissor = NULL;

PFNGLGENTEXTURESPROC glGenTextures = NULL;
PFNGLDELETETEXTURESPROC glDeleteTextures = NULL;
PFNGLBINDTEXTUREPROC glBindTexture = NULL;
PFNGLTEXIMAGE2DPROC glTexImage2D = NULL;
PFNGLTEXPARAMETERIPROC glTexParameteri = NULL;
PFNGLACTIVETEXTUREPROC glActiveTexture = NULL;
PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D = NULL;
PFNGLPIXELSTOREIPROC glPixelStorei = NULL;

PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL;
PFNGLCOMPILESHADERPROC glCompileShader = NULL;
PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;

PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL;
PFNGLGETPROGRAMIVPROC glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL;

PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = NULL;
PFNGLUNIFORM1IPROC glUniform1i = NULL;
PFNGLUNIFORM1FPROC glUniform1f = NULL;
PFNGLUNIFORM2FPROC glUniform2f = NULL;
PFNGLUNIFORM3FPROC glUniform3f = NULL;
PFNGLUNIFORM4FPROC glUniform4f = NULL;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = NULL;

PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = NULL;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = NULL;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = NULL;

PFNGLGENBUFFERSPROC glGenBuffers = NULL;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL;
PFNGLBINDBUFFERPROC glBindBuffer = NULL;
PFNGLBUFFERDATAPROC glBufferData = NULL;
PFNGLBUFFERSUBDATAPROC glBufferSubData = NULL;

PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = NULL;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor = NULL;

PFNGLDRAWARRAYSPROC glDrawArrays = NULL;
PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced = NULL;
PFNGLDRAWELEMENTSPROC glDrawElements = NULL;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced = NULL;

PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = NULL;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = NULL;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = NULL;

#define LOAD_PROC(name, type) do { \
    name = (type)load(#name); \
} while(0)

int gladLoadGLLoader(GLADloadproc load) {
    if (!load) return 0;

    LOAD_PROC(glGetString, PFNGLGETSTRINGPROC);
    LOAD_PROC(glViewport, PFNGLVIEWPORTPROC);
    LOAD_PROC(glClearColor, PFNGLCLEARCOLORPROC);
    LOAD_PROC(glClear, PFNGLCLEARPROC);
    LOAD_PROC(glFlush, PFNGLFLUSHPROC);
    LOAD_PROC(glEnable, PFNGLENABLEPROC);
    LOAD_PROC(glDisable, PFNGLDISABLEPROC);
    LOAD_PROC(glBlendFunc, PFNGLBLENDFUNCPROC);
    LOAD_PROC(glBlendFuncSeparate, PFNGLBLENDFUNCSEPARATEPROC);
    LOAD_PROC(glScissor, PFNGLSCISSORPROC);

    LOAD_PROC(glGenTextures, PFNGLGENTEXTURESPROC);
    LOAD_PROC(glDeleteTextures, PFNGLDELETETEXTURESPROC);
    LOAD_PROC(glBindTexture, PFNGLBINDTEXTUREPROC);
    LOAD_PROC(glTexImage2D, PFNGLTEXIMAGE2DPROC);
    LOAD_PROC(glTexParameteri, PFNGLTEXPARAMETERIPROC);
    LOAD_PROC(glActiveTexture, PFNGLACTIVETEXTUREPROC);
    LOAD_PROC(glTexSubImage2D, PFNGLTEXSUBIMAGE2DPROC);
    LOAD_PROC(glPixelStorei, PFNGLPIXELSTOREIPROC);

    LOAD_PROC(glCreateShader, PFNGLCREATESHADERPROC);
    LOAD_PROC(glShaderSource, PFNGLSHADERSOURCEPROC);
    LOAD_PROC(glCompileShader, PFNGLCOMPILESHADERPROC);
    LOAD_PROC(glGetShaderiv, PFNGLGETSHADERIVPROC);
    LOAD_PROC(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC);
    LOAD_PROC(glDeleteShader, PFNGLDELETESHADERPROC);

    LOAD_PROC(glCreateProgram, PFNGLCREATEPROGRAMPROC);
    LOAD_PROC(glAttachShader, PFNGLATTACHSHADERPROC);
    LOAD_PROC(glLinkProgram, PFNGLLINKPROGRAMPROC);
    LOAD_PROC(glGetProgramiv, PFNGLGETPROGRAMIVPROC);
    LOAD_PROC(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOGPROC);
    LOAD_PROC(glUseProgram, PFNGLUSEPROGRAMPROC);
    LOAD_PROC(glDeleteProgram, PFNGLDELETEPROGRAMPROC);

    LOAD_PROC(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC);
    LOAD_PROC(glUniform1i, PFNGLUNIFORM1IPROC);
    LOAD_PROC(glUniform1f, PFNGLUNIFORM1FPROC);
    LOAD_PROC(glUniform2f, PFNGLUNIFORM2FPROC);
    LOAD_PROC(glUniform3f, PFNGLUNIFORM3FPROC);
    LOAD_PROC(glUniform4f, PFNGLUNIFORM4FPROC);
    LOAD_PROC(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FVPROC);

    LOAD_PROC(glGenVertexArrays, PFNGLGENVERTEXARRAYSPROC);
    LOAD_PROC(glDeleteVertexArrays, PFNGLDELETEVERTEXARRAYSPROC);
    LOAD_PROC(glBindVertexArray, PFNGLBINDVERTEXARRAYPROC);

    LOAD_PROC(glGenBuffers, PFNGLGENBUFFERSPROC);
    LOAD_PROC(glDeleteBuffers, PFNGLDELETEBUFFERSPROC);
    LOAD_PROC(glBindBuffer, PFNGLBINDBUFFERPROC);
    LOAD_PROC(glBufferData, PFNGLBUFFERDATAPROC);
    LOAD_PROC(glBufferSubData, PFNGLBUFFERSUBDATAPROC);

    LOAD_PROC(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC);
    LOAD_PROC(glDisableVertexAttribArray, PFNGLDISABLEVERTEXATTRIBARRAYPROC);
    LOAD_PROC(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC);
    LOAD_PROC(glVertexAttribDivisor, PFNGLVERTEXATTRIBDIVISORPROC);

    LOAD_PROC(glDrawArrays, PFNGLDRAWARRAYSPROC);
    LOAD_PROC(glDrawArraysInstanced, PFNGLDRAWARRAYSINSTANCEDPROC);
    LOAD_PROC(glDrawElements, PFNGLDRAWELEMENTSPROC);
    LOAD_PROC(glDrawElementsInstanced, PFNGLDRAWELEMENTSINSTANCEDPROC);

    LOAD_PROC(glGenFramebuffers, PFNGLGENFRAMEBUFFERSPROC);
    LOAD_PROC(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERSPROC);
    LOAD_PROC(glBindFramebuffer, PFNGLBINDFRAMEBUFFERPROC);
    LOAD_PROC(glFramebufferTexture2D, PFNGLFRAMEBUFFERTEXTURE2DPROC);
    LOAD_PROC(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUSPROC);

    return 1;
}
